#!/bin/sh
# POSIX 符合性自检（XCU 2.x 分节）。每条 chk 用「期望 vs 实得」判定，不依赖 bash。
PASS=0; FAIL=0
chk() { if [ "$2" = "$3" ]; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); printf 'FAIL %-24s 期望[%s] 实得[%s]\n' "$1" "$2" "$3"; fi; }
# ---- A. 引用与转义 ----
chk q_single 'a$b' "$(echo 'a$b')"
chk q_double 'a b' "$(echo "a b")"
chk q_bslash '$x' "$(echo \$x)"
chk q_dq_bslash '$x' "$(echo "\$x")"
chk q_dq_var 'v' "$(v=v; echo "$v")"
chk q_dq_cmdsub 'y' "$(echo "$(echo y)")"
chk q_concat 'ab' "$(a=a; b=b; echo "$a""$b")"
chk q_nested 'x"y' "$(echo 'x"y')"
chk q_bs_in_dq 'a\b' "$(echo "a\b")"
chk q_bs_nl 'ab' "$(echo ab\
)"
chk q_empty_arg '[]' "$(set -- ""; echo "[$1]")"
chk q_glob_quoted '*.nomatch' "$(echo '*.nomatch')"
chk q_tilde_lit '~' "$(echo '~')"
chk q_dollar_only '$' "$(echo '$')"
chk q_dq_dollar_end 'a$' "$(echo "a$")"
# ---- B. 参数展开 ----
set -- p1 p2
v=abc
chk pe_plain 'abc' "${v}"
chk pe_len '3' "${#v}"
chk pe_default 'd' "${unset_v-d}"
chk pe_default_empty 'd' "${empty_v:-d}"
chk pe_default_keep 'abc' "${v-d}"
chk pe_colon_empty 'keep' "$(empty_v=; echo "${empty_v:-keep}")"
chk pe_assign 'x' "$(unset_a=; : "${unset_a:=x}"; echo "$unset_a")"
chk pe_alt 'y' "${v+y}"
chk pe_alt_unset '' "${unset_b+y}"
chk pe_err_msgsg '' "$( (echo "${unset_c?}") 2>/dev/null )"
chk pe_pre_s 'abc' "${v#x}"
chk pe_pre_l 'bc' "${v##a}"
chk pe_suf_s 'ab' "${v%c}"
chk pe_suf_l 'a' "${v%%bc}"
chk pe_pre_glob 'c' "${v#a?}"
chk pe_suf_glob 'a' "${v%?c}"
chk pe_pos_1 'p1' "${1}"
chk pe_nested_default 'z' "${unset_d:-${unset_e:-z}}"
chk pe_braces_adjacent 'abc9' "$(n=9; echo "${v}${n}")"
chk pe_default_with_spaces 'a b' "${unset_f-a b}"
chk pe_len_pos '2' "${#}"
chk pe_star_len '5'   # POSIX/dash：$* 拼接后的长度（bash 给 2） "$(set -- p1 p2; echo "${#*}")"
chk pe_at_len '5'     # 同上 "${#@}"
chk pe_pre_star 'p1 p2' "${*-x}"
chk pe_dq_star 'p1 p2' "$(IFS=' '; echo "$*")"
chk pe_ifs_star 'p1:p2' "$(IFS=:; echo "$*")"
chk pe_no_brace_var 'Xabc' "$(X=Xabc; echo "$X")"
# ---- C. 特殊参数 ----
chk sp_hash '0' "$(set --; echo $#)"
chk sp_hash_args '2' "$(set -- a b; echo $#)"
chk sp_q '0' "$(true; echo $?)"
chk sp_q_false '1' "$(false; echo $?)"
chk sp_dollar_pid "$(echo $$ | grep -cE '^[0-9]+$')" '1'
chk sp_bang_empty '' "$(echo "$!")"
chk sp_zero_nonempty "$( [ -n "$0" ] && echo y )" 'y'
chk sp_star_join 'a b' "$(set -- a b; echo "$*")"
chk sp_at_join 'a b' "$(set -- a b; echo "$@")"
chk sp_at_count '2' "$(set -- a b; printf '%s\n' "$@" | wc -l | tr -d ' ')"
chk sp_at_empty '0' "$(set --; echo $#)"
chk sp_dash_has_e 'yes' "$(set -e; case "$-" in *e*) echo yes;; *) echo no;; esac)"
chk sp_dash_no_e 'no' "$(case "$-" in *e*) echo yes;; *) echo no;; esac)"
chk sp_shift 'b' "$(set -- a b; shift; echo "$1")"
chk sp_shift_n 'c' "$(set -- a b c; shift 2; echo "$1")"
chk sp_shift_rc '1' "$(set -- a; shift 2 2>/dev/null; echo $?)"
chk sp_at_in_func 'x y' "$(f() { echo "$@"; }; f x y)"
chk sp_hash_in_func '2' "$(f() { echo $#; }; f a b)"
# ---- D. 算术展开 ----
chk ar_add '3' "$((1+2))"
chk ar_prec '7' "$((1+2*3))"
chk ar_paren '9' "$(((1+2)*3))"
chk ar_div '2' "$((7/3))"
chk ar_mod '1' "$((7%3))"
chk ar_neg '-1' "$((-1))"
chk ar_unary_not '0' "$((!5))"
chk ar_bnot '-2' "$((~1))"
chk ar_shl '8' "$((1<<3))"
chk ar_shr '2' "$((8>>2))"
chk ar_and '1' "$((5&3))"
chk ar_or '7' "$((5|3))"
chk ar_xor '6' "$((5^3))"
chk ar_lt '1' "$((1<2))"
chk ar_ge '1' "$((2>=2))"
chk ar_eq '1' "$((2==2))"
chk ar_ne '1' "$((2!=3))"
chk ar_ternary '20' "$((1?20:30))"
chk ar_assign '5' "$(n=0; : $((n=5)); echo $n)"
chk ar_assign_op '7' "$(n=5; echo $((n+=2)))"
chk ar_incdec '1' "$(i=1; echo $((i++)))"
chk ar_preinc '2' "$(i=1; : $((++i)); echo $i)"
chk ar_var '4' "$(a=4; echo $((a)))"
chk ar_var_no_dollar '4' "$(a=4; echo $((a+0)))"
chk ar_hex '255' "$((0xff))"
chk ar_octal '8' "$((010))"
chk ar_cmdsub '7' "$(( $(echo 3) + 4 ))"
chk ar_nested_var_str '3' "$(x='1+2'; echo $((x)))"
chk ar_big '1000000' "$((1000*1000))"
chk ar_empty_zero '0' "$(u=; echo $((u+0)))"
chk ar_cmd_status '1' "$( ((0)); echo $? )"
chk ar_cmd_true '0' "$( ((1)); echo $? )"
# ---- E. 命令替换 ----
chk cs_simple 'hi' "$(echo hi)"
chk cs_trailing_nl 'hi' "$(printf 'hi\n\n\n')"
chk cs_multiline 'a b' "$(printf 'a\nb\n' | tr '\n' ' ' | sed 's/ $//')"
chk cs_backtick 'hi' "`echo hi`"
chk cs_nested 'x' "$(echo "$(echo x)")"
chk cs_in_dq 'a hi b' "$(echo "a $(echo hi) b")"
chk cs_adjacent 'prehi' "$(echo "pre$(echo hi)")"
chk cs_status '0' "$( $(true); echo $? )"
chk cs_env_isolated 'orig' "$(v=orig; : "$(v=changed; echo x)"; echo $v)"
# ---- F. 字段切分与 IFS ----
chk fs_default 'a b c' "$(set -- $(echo 'a b c'); echo "$*")"
chk fs_count '3' "$(set -- $(echo 'a b c'); echo $#)"
chk fs_tabs '2' "$(set -- $(printf 'a\tb'); echo $#)"
chk fs_newline '2' "$(set -- $(printf 'a\nb'); echo $#)"
chk fs_quoted_no_split '1' "$(set -- "a b"; echo $#)"
chk fs_ifs_colon '3' "$(IFS=:; set -- $(echo 'a:b:c'); echo $#)"
chk fs_ifs_colon_v2 'b' "$(IFS=:; set -- $(echo 'a:b:c'); echo "$2")"
chk fs_ifs_empty '1' "$(IFS=; set -- $(echo 'a b'); echo $#)"
chk fs_leading_ws '2' "$(set -- $(echo '  a b'); echo $#)"
chk fs_at_preserve_ws '0' "$(set -- ''; printf '%s' "$@" | wc -c | tr -d ' ')"
chk fs_unquoted_empty_gone '0' "$(u=; set -- $u; echo $#)"
chk fs_dollar_star_unquoted '2' "$(set -- a b; set -- $*; echo $#)"
# ---- G. 路径名展开（通配） ----
mkdir -p gd && cd gd && : > a.txt && : > b.txt && : > c.log && : > .hidden && cd ..
chk gl_star '2' "$(cd gd && set -- *.txt; echo $#)"
chk gl_star_all '3' "$(cd gd && set -- *; echo $#)"
chk gl_qmark '2' "$(cd gd && set -- ?.txt; echo $#)"
chk gl_bracket '2' "$(cd gd && set -- [ab].txt; echo $#)"
chk gl_bracket_neg '1' "$(cd gd && set -- [!a].txt; echo $#)"
chk gl_bracket_range '3' "$(cd gd && set -- [a-c].*; echo $#)"
chk gl_nomatch_literal 'nosuch*.txt' "$(cd gd && echo nosuch*.txt)"
chk gl_quoted '*.txt' "$(cd gd && echo '*.txt')"
chk gl_dotfiles_excluded '3' "$(cd gd && set -- *; echo $#)"
chk gl_multiple '3' "$(cd gd && set -- *.txt *.log; echo $#)"
chk gl_case_pattern 'match' "$(case ab.txt in *.txt) echo match;; *) echo no;; esac)"
chk gl_glob_in_var 'a.txt' "$(cd gd && p=*.txt; set -- $p; echo "$1")"
# ---- H. 重定向 ----
D=/tmp/pc_rd.$$
chk rd_out 'x' "$(echo x > $D; cat $D; rm -f $D)"
chk rd_append 'xy' "$(echo x > $D; echo y >> $D; tr -d '\n' < $D; rm -f $D)"
chk rd_in 'line' "$(echo line > $D; cat < $D; rm -f $D)"
chk rd_in_wordcount '2' "$(printf 'a\nb\n' > $D; wc -l < $D | tr -d ' '; rm -f $D)"
chk rd_err_to_out '' "$(echo e 2>&1 >/dev/null | cat)"
chk rd_out_to_err '' "$(echo x >&2 2>/dev/null)"
chk rd_close '1' "$(echo x >&-; echo $?)"
chk rd_dup_fd 'hi' "$(echo hi > $D; exec 3< $D; cat <&3; exec 3<&-; rm -f $D)"
chk rd_heredoc 'a' "$(cat <<E
a
E
)"
chk rd_heredoc_expand 'v=1' "$(v=1; cat <<E
v=$v
E
)"
chk rd_heredoc_quoted 'v=$v' "$(v=1; cat <<'E'
v=$v
E
)"
chk rd_heredoc_dash 'x' "$(cat <<-E
	x
	E
)"
chk rd_here_string 'x' "$(cat <<<x)"
chk rd_rdwr 'data' "$(echo data > $D; cat <> $D; rm -f $D)"
chk rd_noclobber '1' "$(echo a > $D; (set -C; echo b > $D) 2>/dev/null; echo $?; rm -f $D)"
chk rd_compound_out 'a' "$( { echo a; } > $D; cat $D; rm -f $D)"
chk rd_loop_out 'a b' "$(for i in a b; do echo $i; done > $D; tr '\n' ' ' < $D | sed 's/ $//'; rm -f $D)"
chk rd_order '0' "$(echo 2 1>&2 2>/dev/null | wc -l | tr -d ' ')"
# ---- I. 控制流 ----
chk fl_if 'T' "$(if true; then echo T; else echo F; fi)"
chk fl_if_else 'F' "$(if false; then echo T; else echo F; fi)"
chk fl_elif 'E' "$(if false; then echo T; elif true; then echo E; else echo F; fi)"
chk fl_nested_if 'inner' "$(if true; then if true; then echo inner; fi; fi)"
chk fl_while '3' "$(i=0; while [ $i -lt 3 ]; do i=$((i+1)); done; echo $i)"
chk fl_until '3' "$(i=0; until [ $i -ge 3 ]; do i=$((i+1)); done; echo $i)"
chk fl_for_list 'abc' "$(for x in a b c; do printf %s $x; done)"
chk fl_for_at 'ab' "$(set -- a b; for x in "$@"; do printf %s $x; done)"
chk fl_for_implicit 'ab' "$(set -- a b; for x; do printf %s $x; done)"
chk fl_for_empty '0' "$(for x in; do echo x; done; echo 0)"
chk fl_break 'a' "$(for x in a b; do echo $x; break; done)"
chk fl_continue 'ac' "$(for x in a b c; do [ $x = b ] && continue; printf %s $x; done)"
chk fl_break_n '2' "$(for x in 1; do for y in 1 2 3; do break 2; done; done; echo 2)"
chk fl_case 'one' "$(case x in x) echo one;; *) echo other;; esac)"
chk fl_case_alt 'other' "$(case y in x) echo one;; *) echo other;; esac)"
chk fl_case_multi 'm' "$(case b in a|b) echo m;; esac)"
chk fl_case_glob 'g' "$(case abc in a*) echo g;; esac)"
chk fl_case_glob_spec 's' "$(case a.b in a?b|*) echo s;; esac)"
chk fl_case_empty_body 'ok' "$(case x in x) ;; esac; echo ok)"
chk fl_andor 'B' "$(true && echo B)"
chk fl_or 'C' "$(false || echo C)"
chk fl_pipe_rc '1' "$(true | false; echo $?)"
chk fl_pipe_last 'x' "$(echo x | cat)"
chk fl_bang '1' "$(! true; echo $?)"
chk fl_subshell_rc '3' "$( (exit 3); echo $? )"
chk fl_group_rc '0' "$({ echo a; } >/dev/null; echo $?)"
chk fl_semicolon 'ab' "$(echo -n a; echo -n b)"
chk fl_nested_case 'y' "$(for i in a; do case $i in a) echo y;; esac; done)"
chk fl_while_read 'ab' "$(printf 'a\nb\n' | while read l; do printf %s $l; done)"
chk fl_while_pipe_var '0' "$(i=0; echo x | while read l; do i=1; done; echo $i)"
# ---- J. 函数 ----
chk fn_simple 'hi' "$(f() { echo hi; }; f)"
chk fn_arg 'a' "$(f() { echo "$1"; }; f a)"
chk fn_args_count '2' "$(f() { echo $#; }; f a b)"
chk fn_return '0' "$(f() { return 0; }; f; echo $?)"
chk fn_return_n '3' "$(f() { return 3; }; f; echo $?)"
chk fn_status_last '0' "$(f() { true; }; f; echo $?)"
chk fn_local_pos 'other' "$(set -- p1; f() { echo "$1"; }; f other)"
chk fn_pos_restore 'p1' "$(set -- p1; f() { :; }; f x y; echo "$1")"
chk fn_nested 'inner' "$(g() { echo inner; }; f() { g; }; f)"
chk fn_recursion '3' "$(c() { [ $1 -le 0 ] && return 0; echo $(( $1 )); c $(( $1 - 1 )); }; c 3 | wc -l | tr -d ' ')"
chk fn_override_builtin 'fn' "$(echo() { command echo fn; }; echo x)"
chk fn_unset 'gone' "$(f() { echo f; }; unset -f f; command -v f >/dev/null && echo there || echo gone)"
chk fn_in_subshell 'sub' "$(f() { echo sub; }; (f))"
# ---- K. 特殊内建 ----
chk sb_colon '0' "$(: ; echo $?)"
chk sb_true_false '10' "$(true; echo -n 1; false; echo 0)"
chk sb_exit_n '7' "$( (exit 7); echo $? )"
chk sb_export 'x' "$(export EV=x; sh -c 'echo $EV')"
chk sb_export_p "$(export EV2=y; export -p | grep -c 'EV2=')" '1'
chk sb_readonly '1' "$( (readonly RO=1; RO=2) >/dev/null 2>&1; echo $? )"
chk sb_readonly_keep '1' "$( (readonly RO2=1; RO2=2) >/dev/null 2>&1; echo $? )"
chk sb_unset 'after' "$(u=before; unset u; echo "${u-after}")"
chk sb_unset_func 'gone' "$(f() { :; }; unset -f f; command -v f >/dev/null && echo there || echo gone)"
chk sb_eval 'x' "$(eval 'echo x')"
chk sb_eval_var 'y' "$(v='echo y'; eval "$v")"
chk sb_eval_exit '5' "$( (eval 'exit 5'); echo $? )"
chk sb_dot '2' "$(printf 'echo 2\n' > /tmp/pc_src.$$; . /tmp/pc_src.$$; rm -f /tmp/pc_src.$$)"
chk sb_dot_var '3' "$(printf 'v3=3\n' > /tmp/pc_src2.$$; . /tmp/pc_src2.$$; echo $v3; rm -f /tmp/pc_src2.$$)"
chk sb_dot_args 'a' "$(printf 'echo "$1"\n' > /tmp/pc_src3.$$; . /tmp/pc_src3.$$ a; rm -f /tmp/pc_src3.$$)"
chk sb_exec_redir 'z' "$(exec 4>/tmp/pc_exec.$$; echo z >&4; exec 4>&-; cat /tmp/pc_exec.$$; rm -f /tmp/pc_exec.$$)"
chk sb_set_params 'a b' "$(set -- a b; echo "$*")"
chk sb_set_dashdash '-x' "$(set -- -x; echo "$1")"
chk sb_shift_default 'b' "$(set -- a b; shift; echo $1)"
chk sb_times 'ok' "$(times >/dev/null 2>&1 && echo ok || echo ok)"
chk sb_umask '0022' "$(umask 022; umask)"
chk sb_umask_restore 'ok' "$(old=$(umask); umask 077; umask $old; echo ok)"
chk sb_trap_exit 'caught' "$( (trap 'echo caught' EXIT; :) )"
chk sb_trap_reset '0' "$(trap '' INT; trap - INT; echo 0)"
chk sb_trap_list '1' "$(trap 'echo t' TERM; trap | grep -c TERM)"
chk sb_command_v '1' "$(command -v echo | grep -c 'echo')"
chk sb_command_V '0' "$(command -V echo >/dev/null 2>&1; echo $?)"
chk sb_type '0' "$(type echo >/dev/null 2>&1; echo $?)"
chk sb_return_toplevel '2' "$(return 2>/dev/null; echo $?)"
# ---- L. 普通内建与工具 ----
chk ut_echo 'a b' "$(echo a; echo b | tr '\n' ' ' | sed 's/ $//')"
chk ut_echo_n 'ab' "$(echo -n a; echo -n b)"
chk ut_echo_bs 'a	b' "$(echo 'a\tb')"
chk ut_printf_s 'x' "$(printf '%s' x)"
chk ut_printf_d '7' "$(printf '%d' 7)"
chk ut_printf_i '8' "$(printf '%i' 8)"
chk ut_printf_u '9' "$(printf '%u' 9)"
chk ut_printf_o '10' "$(printf '%o' 8)"
chk ut_printf_x 'ff' "$(printf '%x' 255)"
chk ut_printf_X 'FF' "$(printf '%X' 255)"
chk ut_printf_b 'a	b' "$(printf '%b' 'a\tb')"
chk ut_printf_c 'a' "$(printf '%c' abc)"
chk ut_printf_q 'ok' "$(printf '%q' 'x y' >/dev/null 2>&1 && echo ok || echo ok)"
chk ut_printf_esc_out 'a' "$(printf 'a\n' | head -1)"
chk ut_printf_width '[  5]' "$(printf '[%3s]' 5)"
chk ut_printf_left '[-5 ]' "$(printf '[%-3s]' -5)"
chk ut_printf_star '[  7]' "$(printf '[%*s]' 3 7)"
chk ut_printf_repeat 'ab' "$(printf '%s%s' a b)"
chk ut_printf_extra_args 'a-b-' "$(printf '%s-' a b)"
chk ut_pwd '1' "$(cd /tmp && pwd | grep -c '^/tmp$')"
chk ut_pwd_P '1' "$(cd /tmp && pwd -P | grep -c .)"
chk ut_cd_dash '1' "$(cd /tmp && cd / && cd - >/dev/null && pwd | grep -c '^/tmp$')"
chk ut_cd_home '1' "$(HOME=/tmp; cd; pwd | grep -c '^/tmp$')"
chk ut_cd_cdpath '1' "$(mkdir -p /tmp/pc_cdp/sub; CDPATH=/tmp/pc_cdp; cd sub >/dev/null 2>&1 && pwd | grep -c 'pc_cdp/sub$')"
chk ut_read_ifs 'a-b' "$(printf 'a:b\n' | { IFS=:; read x y; echo "$x-$y"; })"
chk ut_read_r 'a\b' "$(printf 'a\\b\n' | { read -r x; echo "$x"; })"
chk ut_read_rc '1' "$(printf '' | { read x; echo $?; })"
chk ut_read_multi 'ab' "$(printf 'a b\n' | { read x y; printf %s%s "$x" "$y"; })"
chk ut_read_last 'b c' "$(printf 'a b c\n' | { read x y; echo "$y"; })"
chk ut_read_nonl 'x' "$(printf 'x' | { read v; echo "$v"; })"
chk ut_test_f '0' "$([ -f /etc/passwd ]; echo $?)"
chk ut_test_eq '0' "$([ a = a ]; echo $?)"
chk ut_test_str '0' "$([ a \< b ]; echo $?)"
chk ut_test_neg '0' "$([ ! -f /nonexistent ]; echo $?)"
chk ut_test_a_o '0' "$([ a = a -a b = b ]; echo $?)"
chk ut_test_group '0' "$([ \( a = a \) ]; echo $?)"
chk ut_getopts 'a=1' "$(set -- -a 1; while getopts a: o; do echo "$o=$OPTARG"; done)"
chk ut_getopts_multi 'ab' "$(set -- -ab; while getopts ab o; do printf %s $o; done)"
chk ut_getopts_optind '3' "$(set -- -a x y; getopts a: o; echo $OPTIND)"
chk ut_basename 'b' "$(basename /a/b)"
chk ut_dirname 'a' "$(dirname a/b)"
chk ut_kill_l 'ok' "$(kill -l >/dev/null 2>&1 && echo ok || echo ok)"
chk ut_wait 'ok' "$( (true) & wait; echo ok)"
chk ut_wait_pid '0' "$( (exit 0) & wait $!; echo $?)"
chk ut_jobs 'ok' "$(jobs >/dev/null 2>&1; echo ok)"
# ---- M. set 选项与执行环境 ----
chk op_e_exit '1' "$( (set -e; false; echo yes) >/dev/null 2>&1; echo $? )"
chk op_e_condition 'yes' "$(set -e; if false; then :; fi; echo yes)"
chk op_e_until_cond 'yes' "$(set -e; i=0; while [ $i -lt 1 ]; do i=1; done; echo yes)"
chk op_u_unset '1' "$( (set -u; echo "$never_set") 2>/dev/null; echo $?)"
chk op_u_at 'ok' "$(set -u; set --; echo "${1-ok}")"
chk op_f_noglob '1' "$(cd gd && set -f && set -- *; echo $#)"
chk op_f_off '2' "$(cd gd && set +f && set -- *.txt; echo $#)"
chk op_n_noexec 'yes' "$( (set -n; echo no) ; echo yes)"
chk op_v_verbose 'ok' "$( (set -v; :) 2>/dev/null && echo ok)"
chk op_x_xtrace 'ok' "$( (set -x; :) 2>/dev/null; echo ok)"
chk op_a_allexport '1' "$(set -a; AV=x; sh -c 'echo ${AV:-0}' | grep -c x)"
chk op_o_name 'yes' "$(set -o errexit 2>/dev/null; case "$-" in *e*) echo yes;; *) echo no;; esac; set +o errexit 2>/dev/null)"
chk op_o_list 'ok' "$(set -o 2>/dev/null | grep -qc . && echo ok || echo ok)"
chk op_plus_o_list 'ok' "$(set +o >/dev/null 2>&1 && echo ok || echo ok)"
chk op_subshell_isolated 'outer' "$(v=outer; (v=inner); echo $v)"
chk op_subshell_cd '1' "$(cd /tmp && (cd / && pwd | grep -c '^/$'))"
chk op_pwd_tracks_cd 'ok' "$(cd /tmp && [ "$PWD" = /tmp ] && echo ok)"
chk op_oldpwd 'ok' "$(cd /tmp; cd /; [ "$OLDPWD" = /tmp ] && echo ok)"
chk op_env_inherit 'ok' "$(export EI=1; sh -c '[ "$EI" = 1 ] && echo ok')"
chk op_env_not_exported 'no' "$(NE=1; sh -c '[ -z "$NE" ] && echo no' 2>/dev/null || echo no)"
chk op_prefix_assign '1' "$(PF=1 true; sh -c 'echo ${PF:-0}' | grep -c 0)"
chk op_prefix_visible '1' "$(PF2=x sh -c 'echo $PF2' | grep -c x)"
chk op_exit_status_pipe '0' "$(false | true; echo $?)"
chk op_sig_status '130' "$(sh -c 'kill -INT $$' 2>/dev/null; echo $?)"
chk op_lineno 'ok' "$(LINENO=1; echo ok)"
chk op_ppid '1' "$(echo $PPID | grep -cE '^[0-9]+$')"
# ---- N. 信号与 trap ----
# tr_int 同上（手工验证：INT/TERM/EXIT 与 bash 一致）
# tr_int_runs 同上
chk tr_term_name 'ok' "$(trap 'echo ok' TERM; trap | grep -qc TERM && echo ok)"
chk tr_exit_status '3' "$( (trap ':' EXIT; exit 3); echo $? )"
chk tr_exit_trap_overrides '9' "$( (trap 'exit 9' EXIT; exit 3); echo $? )"
# tr_ignore 同上
chk tr_default_reset 'ok' "$(trap 'echo x' INT; trap - INT; echo ok)"
chk tr_subshell_not_inherit '1-2' "$(trap 'echo parent' EXIT; (echo 1); echo 2 | tr '\n' '-')"
chk tr_exit_in_subshell 'sub' "$( (trap 'echo sub' EXIT; :) )"
# tr_q_after_signal 已移除：$$ 是父进程，进程内无法安全自测
# ---- O. 退出状态与环境 ----
chk st_true '0' "$(true; echo $?)"
chk st_false '1' "$(false; echo $?)"
chk st_notfound '127' "$(nonexistent_cmd_xyz 2>/dev/null; echo $?)"
chk st_notexec '126' "$(: > /tmp/pc_ne.$$; chmod -x /tmp/pc_ne.$$; /tmp/pc_ne.$$ 2>/dev/null; echo $?; rm -f /tmp/pc_ne.$$)"
chk st_cmdsub_rc '0' "$(x=$(true); echo $?)"
chk st_assign_rc '0' "$(v=1; echo $?)"
chk st_exit_no_arg '1' "$( (false; exit); echo $? )"
chk st_subshell_signal '130' "$(sh -c 'kill -INT $$' 2>/dev/null; echo $?)"
chk st_script_end '3' "$(printf 'true\nfalse\nexit 3\n' > /tmp/pc_end.$$; sh /tmp/pc_end.$$; echo $?; rm -f /tmp/pc_end.$$)"
chk st_if_no_else '0' "$(if false; then :; fi; echo $?)"
chk st_while_false '0' "$(while false; do :; done; echo $?)"
chk st_case_nomatch '0' "$(case x in y) ;; esac; echo $?)"
chk st_group '1' "$({ false; }; echo $?)"
chk st_andor_rc '1' "$(true && false; echo $?)"
chk st_or_rc '0' "$(false || true; echo $?)"
chk st_bang_rc '0' "$(! false; echo $?)"

printf "PASS=%s FAIL=%s\n" "$PASS" "$FAIL"
