# ---- B. 参数展开 ----
set -- p1 p2
v=abc
chk pe_plain 'abc' "${v}"
chk pe_len '3' "${#v}"
chk pe_default 'd' "${unset_v-d}"
chk pe_default_empty 'd' "${empty_v:-d}"
chk pe_default_keep 'abc' "${v-d}"
chk pe_colon_empty 'keep' "$(empty_v=; echo "${empty_v:-keep}")"
chk pe_assign 'x' "$(unset_a=; : "${unset_a:=x}"; echo "$unset_a")"
chk pe_alt 'y' "${v+y}"
chk pe_alt_unset '' "${unset_b+y}"
chk pe_err_msgsg '' "$( (echo "${unset_c?}") 2>/dev/null )"
chk pe_pre_s 'abc' "${v#x}"
chk pe_pre_l 'bc' "${v##a}"
chk pe_suf_s 'ab' "${v%c}"
chk pe_suf_l 'a' "${v%%bc}"
chk pe_pre_glob 'c' "${v#a?}"
chk pe_suf_glob 'a' "${v%?c}"
chk pe_pos_1 'p1' "${1}"
chk pe_nested_default 'z' "${unset_d:-${unset_e:-z}}"
chk pe_braces_adjacent 'abc9' "$(n=9; echo "${v}${n}")"
chk pe_default_with_spaces 'a b' "${unset_f-a b}"
chk pe_len_pos '2' "${#}"
chk pe_star_len '5'   # POSIX/dash：$* 拼接后的长度（bash 给 2） "$(set -- p1 p2; echo "${#*}")"
chk pe_at_len '5'     # 同上 "${#@}"
chk pe_pre_star 'p1 p2' "${*-x}"
chk pe_dq_star 'p1 p2' "$(IFS=' '; echo "$*")"
chk pe_ifs_star 'p1:p2' "$(IFS=:; echo "$*")"
chk pe_no_brace_var 'Xabc' "$(X=Xabc; echo "$X")"
