# ---- D. 算术展开 ----
chk ar_add '3' "$((1+2))"
chk ar_prec '7' "$((1+2*3))"
chk ar_paren '9' "$(((1+2)*3))"
chk ar_div '2' "$((7/3))"
chk ar_mod '1' "$((7%3))"
chk ar_neg '-1' "$((-1))"
chk ar_unary_not '0' "$((!5))"
chk ar_bnot '-2' "$((~1))"
chk ar_shl '8' "$((1<<3))"
chk ar_shr '2' "$((8>>2))"
chk ar_and '1' "$((5&3))"
chk ar_or '7' "$((5|3))"
chk ar_xor '6' "$((5^3))"
chk ar_lt '1' "$((1<2))"
chk ar_ge '1' "$((2>=2))"
chk ar_eq '1' "$((2==2))"
chk ar_ne '1' "$((2!=3))"
chk ar_ternary '20' "$((1?20:30))"
chk ar_assign '5' "$(n=0; : $((n=5)); echo $n)"
chk ar_assign_op '7' "$(n=5; echo $((n+=2)))"
chk ar_incdec '1' "$(i=1; echo $((i++)))"
chk ar_preinc '2' "$(i=1; : $((++i)); echo $i)"
chk ar_var '4' "$(a=4; echo $((a)))"
chk ar_var_no_dollar '4' "$(a=4; echo $((a+0)))"
chk ar_hex '255' "$((0xff))"
chk ar_octal '8' "$((010))"
chk ar_cmdsub '7' "$(( $(echo 3) + 4 ))"
chk ar_nested_var_str '3' "$(x='1+2'; echo $((x)))"
chk ar_big '1000000' "$((1000*1000))"
chk ar_empty_zero '0' "$(u=; echo $((u+0)))"
chk ar_cmd_status '1' "$( ((0)); echo $? )"
chk ar_cmd_true '0' "$( ((1)); echo $? )"
