# ---- I. 控制流 ----
chk fl_if 'T' "$(if true; then echo T; else echo F; fi)"
chk fl_if_else 'F' "$(if false; then echo T; else echo F; fi)"
chk fl_elif 'E' "$(if false; then echo T; elif true; then echo E; else echo F; fi)"
chk fl_nested_if 'inner' "$(if true; then if true; then echo inner; fi; fi)"
chk fl_while '3' "$(i=0; while [ $i -lt 3 ]; do i=$((i+1)); done; echo $i)"
chk fl_until '3' "$(i=0; until [ $i -ge 3 ]; do i=$((i+1)); done; echo $i)"
chk fl_for_list 'abc' "$(for x in a b c; do printf %s $x; done)"
chk fl_for_at 'ab' "$(set -- a b; for x in "$@"; do printf %s $x; done)"
chk fl_for_implicit 'ab' "$(set -- a b; for x; do printf %s $x; done)"
chk fl_for_empty '0' "$(for x in; do echo x; done; echo 0)"
chk fl_break 'a' "$(for x in a b; do echo $x; break; done)"
chk fl_continue 'ac' "$(for x in a b c; do [ $x = b ] && continue; printf %s $x; done)"
chk fl_break_n '2' "$(for x in 1; do for y in 1 2 3; do break 2; done; done; echo 2)"
chk fl_case 'one' "$(case x in x) echo one;; *) echo other;; esac)"
chk fl_case_alt 'other' "$(case y in x) echo one;; *) echo other;; esac)"
chk fl_case_multi 'm' "$(case b in a|b) echo m;; esac)"
chk fl_case_glob 'g' "$(case abc in a*) echo g;; esac)"
chk fl_case_glob_spec 's' "$(case a.b in a?b|*) echo s;; esac)"
chk fl_case_empty_body 'ok' "$(case x in x) ;; esac; echo ok)"
chk fl_andor 'B' "$(true && echo B)"
chk fl_or 'C' "$(false || echo C)"
chk fl_pipe_rc '1' "$(true | false; echo $?)"
chk fl_pipe_last 'x' "$(echo x | cat)"
chk fl_bang '1' "$(! true; echo $?)"
chk fl_subshell_rc '3' "$( (exit 3); echo $? )"
chk fl_group_rc '0' "$({ echo a; } >/dev/null; echo $?)"
chk fl_semicolon 'ab' "$(echo -n a; echo -n b)"
chk fl_nested_case 'y' "$(for i in a; do case $i in a) echo y;; esac; done)"
chk fl_while_read 'ab' "$(printf 'a\nb\n' | while read l; do printf %s $l; done)"
chk fl_while_pipe_var '0' "$(i=0; echo x | while read l; do i=1; done; echo $i)"
