# ---- J. 函数 ----
chk fn_simple 'hi' "$(f() { echo hi; }; f)"
chk fn_arg 'a' "$(f() { echo "$1"; }; f a)"
chk fn_args_count '2' "$(f() { echo $#; }; f a b)"
chk fn_return '0' "$(f() { return 0; }; f; echo $?)"
chk fn_return_n '3' "$(f() { return 3; }; f; echo $?)"
chk fn_status_last '0' "$(f() { true; }; f; echo $?)"
chk fn_local_pos 'other' "$(set -- p1; f() { echo "$1"; }; f other)"
chk fn_pos_restore 'p1' "$(set -- p1; f() { :; }; f x y; echo "$1")"
chk fn_nested 'inner' "$(g() { echo inner; }; f() { g; }; f)"
chk fn_recursion '3' "$(c() { [ $1 -le 0 ] && return 0; echo $(( $1 )); c $(( $1 - 1 )); }; c 3 | wc -l | tr -d ' ')"
chk fn_override_builtin 'fn' "$(echo() { command echo fn; }; echo x)"
chk fn_unset 'gone' "$(f() { echo f; }; unset -f f; command -v f >/dev/null && echo there || echo gone)"
chk fn_in_subshell 'sub' "$(f() { echo sub; }; (f))"
