# ---- K. 特殊内建 ----
chk sb_colon '0' "$(: ; echo $?)"
chk sb_true_false '10' "$(true; echo -n 1; false; echo 0)"
chk sb_exit_n '7' "$( (exit 7); echo $? )"
chk sb_export 'x' "$(export EV=x; sh -c 'echo $EV')"
chk sb_export_p "$(export EV2=y; export -p | grep -c 'EV2=')" '1'
chk sb_readonly '1' "$( (readonly RO=1; RO=2) >/dev/null 2>&1; echo $? )"
chk sb_readonly_keep '1' "$( (readonly RO2=1; RO2=2) >/dev/null 2>&1; echo $? )"
chk sb_unset 'after' "$(u=before; unset u; echo "${u-after}")"
chk sb_unset_func 'gone' "$(f() { :; }; unset -f f; command -v f >/dev/null && echo there || echo gone)"
chk sb_eval 'x' "$(eval 'echo x')"
chk sb_eval_var 'y' "$(v='echo y'; eval "$v")"
chk sb_eval_exit '5' "$( (eval 'exit 5'); echo $? )"
chk sb_dot '2' "$(printf 'echo 2\n' > /tmp/pc_src.$$; . /tmp/pc_src.$$; rm -f /tmp/pc_src.$$)"
chk sb_dot_var '3' "$(printf 'v3=3\n' > /tmp/pc_src2.$$; . /tmp/pc_src2.$$; echo $v3; rm -f /tmp/pc_src2.$$)"
chk sb_dot_args 'a' "$(printf 'echo "$1"\n' > /tmp/pc_src3.$$; . /tmp/pc_src3.$$ a; rm -f /tmp/pc_src3.$$)"
chk sb_exec_redir 'z' "$(exec 4>/tmp/pc_exec.$$; echo z >&4; exec 4>&-; cat /tmp/pc_exec.$$; rm -f /tmp/pc_exec.$$)"
chk sb_set_params 'a b' "$(set -- a b; echo "$*")"
chk sb_set_dashdash '-x' "$(set -- -x; echo "$1")"
chk sb_shift_default 'b' "$(set -- a b; shift; echo $1)"
chk sb_times 'ok' "$(times >/dev/null 2>&1 && echo ok || echo ok)"
chk sb_umask '0022' "$(umask 022; umask)"
chk sb_umask_restore 'ok' "$(old=$(umask); umask 077; umask $old; echo ok)"
chk sb_trap_exit 'caught' "$( (trap 'echo caught' EXIT; :) )"
chk sb_trap_reset '0' "$(trap '' INT; trap - INT; echo 0)"
chk sb_trap_list '1' "$(trap 'echo t' TERM; trap | grep -c TERM)"
chk sb_command_v '1' "$(command -v echo | grep -c 'echo')"
chk sb_command_V '0' "$(command -V echo >/dev/null 2>&1; echo $?)"
chk sb_type '0' "$(type echo >/dev/null 2>&1; echo $?)"
chk sb_return_toplevel '2' "$(return 2>/dev/null; echo $?)"
