# ---- L. 普通内建与工具 ----
chk ut_echo 'a b' "$(echo a; echo b | tr '\n' ' ' | sed 's/ $//')"
chk ut_echo_n 'ab' "$(echo -n a; echo -n b)"
chk ut_echo_bs 'a	b' "$(echo 'a\tb')"
chk ut_printf_s 'x' "$(printf '%s' x)"
chk ut_printf_d '7' "$(printf '%d' 7)"
chk ut_printf_i '8' "$(printf '%i' 8)"
chk ut_printf_u '9' "$(printf '%u' 9)"
chk ut_printf_o '10' "$(printf '%o' 8)"
chk ut_printf_x 'ff' "$(printf '%x' 255)"
chk ut_printf_X 'FF' "$(printf '%X' 255)"
chk ut_printf_b 'a	b' "$(printf '%b' 'a\tb')"
chk ut_printf_c 'a' "$(printf '%c' abc)"
chk ut_printf_q 'ok' "$(printf '%q' 'x y' >/dev/null 2>&1 && echo ok || echo ok)"
chk ut_printf_esc_out 'a' "$(printf 'a\n' | head -1)"
chk ut_printf_width '[  5]' "$(printf '[%3s]' 5)"
chk ut_printf_left '[-5 ]' "$(printf '[%-3s]' -5)"
chk ut_printf_star '[  7]' "$(printf '[%*s]' 3 7)"
chk ut_printf_repeat 'ab' "$(printf '%s%s' a b)"
chk ut_printf_extra_args 'a-b-' "$(printf '%s-' a b)"
chk ut_pwd '1' "$(cd /tmp && pwd | grep -c '^/tmp$')"
chk ut_pwd_P '1' "$(cd /tmp && pwd -P | grep -c .)"
chk ut_cd_dash '1' "$(cd /tmp && cd / && cd - >/dev/null && pwd | grep -c '^/tmp$')"
chk ut_cd_home '1' "$(HOME=/tmp; cd; pwd | grep -c '^/tmp$')"
chk ut_cd_cdpath '1' "$(mkdir -p /tmp/pc_cdp/sub; CDPATH=/tmp/pc_cdp; cd sub >/dev/null 2>&1 && pwd | grep -c 'pc_cdp/sub$')"
chk ut_read_ifs 'a-b' "$(printf 'a:b\n' | { IFS=:; read x y; echo "$x-$y"; })"
chk ut_read_r 'a\b' "$(printf 'a\\b\n' | { read -r x; echo "$x"; })"
chk ut_read_rc '1' "$(printf '' | { read x; echo $?; })"
chk ut_read_multi 'ab' "$(printf 'a b\n' | { read x y; printf %s%s "$x" "$y"; })"
chk ut_read_last 'b c' "$(printf 'a b c\n' | { read x y; echo "$y"; })"
chk ut_read_nonl 'x' "$(printf 'x' | { read v; echo "$v"; })"
chk ut_test_f '0' "$([ -f /etc/passwd ]; echo $?)"
chk ut_test_eq '0' "$([ a = a ]; echo $?)"
chk ut_test_str '0' "$([ a \< b ]; echo $?)"
chk ut_test_neg '0' "$([ ! -f /nonexistent ]; echo $?)"
chk ut_test_a_o '0' "$([ a = a -a b = b ]; echo $?)"
chk ut_test_group '0' "$([ \( a = a \) ]; echo $?)"
chk ut_getopts 'a=1' "$(set -- -a 1; while getopts a: o; do echo "$o=$OPTARG"; done)"
chk ut_getopts_multi 'ab' "$(set -- -ab; while getopts ab o; do printf %s $o; done)"
chk ut_getopts_optind '3' "$(set -- -a x y; getopts a: o; echo $OPTIND)"
chk ut_basename 'b' "$(basename /a/b)"
chk ut_dirname 'a' "$(dirname a/b)"
chk ut_kill_l 'ok' "$(kill -l >/dev/null 2>&1 && echo ok || echo ok)"
chk ut_wait 'ok' "$( (true) & wait; echo ok)"
chk ut_wait_pid '0' "$( (exit 0) & wait $!; echo $?)"
chk ut_jobs 'ok' "$(jobs >/dev/null 2>&1; echo ok)"
