# ---- M. set 选项与执行环境 ----
chk op_e_exit '1' "$( (set -e; false; echo yes) >/dev/null 2>&1; echo $? )"
chk op_e_condition 'yes' "$(set -e; if false; then :; fi; echo yes)"
chk op_e_until_cond 'yes' "$(set -e; i=0; while [ $i -lt 1 ]; do i=1; done; echo yes)"
chk op_u_unset '1' "$( (set -u; echo "$never_set") 2>/dev/null; echo $?)"
chk op_u_at 'ok' "$(set -u; set --; echo "${1-ok}")"
chk op_f_noglob '1' "$(cd gd && set -f && set -- *; echo $#)"
chk op_f_off '2' "$(cd gd && set +f && set -- *.txt; echo $#)"
chk op_n_noexec 'yes' "$( (set -n; echo no) ; echo yes)"
chk op_v_verbose 'ok' "$( (set -v; :) 2>/dev/null && echo ok)"
chk op_x_xtrace 'ok' "$( (set -x; :) 2>/dev/null; echo ok)"
chk op_a_allexport '1' "$(set -a; AV=x; sh -c 'echo ${AV:-0}' | grep -c x)"
chk op_o_name 'yes' "$(set -o errexit 2>/dev/null; case "$-" in *e*) echo yes;; *) echo no;; esac; set +o errexit 2>/dev/null)"
chk op_o_list 'ok' "$(set -o 2>/dev/null | grep -qc . && echo ok || echo ok)"
chk op_plus_o_list 'ok' "$(set +o >/dev/null 2>&1 && echo ok || echo ok)"
chk op_subshell_isolated 'outer' "$(v=outer; (v=inner); echo $v)"
chk op_subshell_cd '1' "$(cd /tmp && (cd / && pwd | grep -c '^/$'))"
chk op_pwd_tracks_cd 'ok' "$(cd /tmp && [ "$PWD" = /tmp ] && echo ok)"
chk op_oldpwd 'ok' "$(cd /tmp; cd /; [ "$OLDPWD" = /tmp ] && echo ok)"
chk op_env_inherit 'ok' "$(export EI=1; sh -c '[ "$EI" = 1 ] && echo ok')"
chk op_env_not_exported 'no' "$(NE=1; sh -c '[ -z "$NE" ] && echo no' 2>/dev/null || echo no)"
chk op_prefix_assign '1' "$(PF=1 true; sh -c 'echo ${PF:-0}' | grep -c 0)"
chk op_prefix_visible '1' "$(PF2=x sh -c 'echo $PF2' | grep -c x)"
chk op_exit_status_pipe '0' "$(false | true; echo $?)"
chk op_sig_status '130' "$(sh -c 'kill -INT $$' 2>/dev/null; echo $?)"
chk op_lineno 'ok' "$(LINENO=1; echo ok)"
chk op_ppid '1' "$(echo $PPID | grep -cE '^[0-9]+$')"
