# ---- O. 退出状态与环境 ----
chk st_true '0' "$(true; echo $?)"
chk st_false '1' "$(false; echo $?)"
chk st_notfound '127' "$(nonexistent_cmd_xyz 2>/dev/null; echo $?)"
chk st_notexec '126' "$(: > /tmp/pc_ne.$$; chmod -x /tmp/pc_ne.$$; /tmp/pc_ne.$$ 2>/dev/null; echo $?; rm -f /tmp/pc_ne.$$)"
chk st_cmdsub_rc '0' "$(x=$(true); echo $?)"
chk st_assign_rc '0' "$(v=1; echo $?)"
chk st_exit_no_arg '1' "$( (false; exit); echo $? )"
chk st_subshell_signal '130' "$(sh -c 'kill -INT $$' 2>/dev/null; echo $?)"
chk st_script_end '3' "$(printf 'true\nfalse\nexit 3\n' > /tmp/pc_end.$$; sh /tmp/pc_end.$$; echo $?; rm -f /tmp/pc_end.$$)"
chk st_if_no_else '0' "$(if false; then :; fi; echo $?)"
chk st_while_false '0' "$(while false; do :; done; echo $?)"
chk st_case_nomatch '0' "$(case x in y) ;; esac; echo $?)"
chk st_group '1' "$({ false; }; echo $?)"
chk st_andor_rc '1' "$(true && false; echo $?)"
chk st_or_rc '0' "$(false || true; echo $?)"
chk st_bang_rc '0' "$(! false; echo $?)"
